services:
  assets:
    build: .
    container_name: kpihx-labs-assets
    restart: unless-stopped
    # volumes are removed to favor baked-in config (reliability)
    labels:
      - "traefik.enable=true"

      # --- Accès hybride (Interne .homelab + Public .com) ---
      - "traefik.http.routers.assets.rule=Host(`assets.homelab`) || Host(`assets.kpihx-labs.com`)"
      - "traefik.http.routers.assets.entrypoints=websecure"
      - "traefik.http.routers.assets.tls=true"
      
      # --- Middlewares ---
      # On garde le mot de passe Traefik par défaut (Double Sécu)
      # - "traefik.http.routers.assets.middlewares=auth"

      # --- Service ---
      - "traefik.http.routers.assets.service=assets"
      - "traefik.http.services.assets.loadbalancer.server.port=80"

    networks:
      - proxy

networks:
  proxy:
    external: true
